INSERT INTO weapons (name, type, attack_bonus, defense_bonus, magic_bonus, speed_bonus, image_path)
VALUES 
('Rusty Short Sword', 'Sword', 2, 0, 0, 1, '/static/images/weapons/rusty_short_sword.png'),
('Iron Dagger', 'Sword', 4, 0, 0, 2, '/static/images/weapons/iron_dagger.png'),
('Steel Broadsword', 'Sword', 6, 1, 0, 1, '/static/images/weapons/steel_broadsword.png'),
('Bronze Scimitar', 'Sword', 8, 1, 0, 2, '/static/images/weapons/bronze_scimitar.png'),
('Silver Rapier', 'Sword', 10, 1, 1, 3, '/static/images/weapons/silver_rapier.png'),
('Knight''s Longsword', 'Sword', 12, 2, 0, 2, '/static/images/weapons/knights_longsword.png'),
('Blazing Falchion', 'Sword', 14, 3, 2, 1, '/static/images/weapons/blazing_falchion.png'),
('Dragonbone Saber', 'Sword', 16, 3, 1, 3, '/static/images/weapons/dragonbone_saber.png'),
('Mystic Blade', 'Sword', 18, 2, 5, 2, '/static/images/weapons/mystic_blade.png'),
('Runed Greatsword', 'Sword', 20, 4, 3, 1, '/static/images/weapons/runed_greatsword.png'),
('Moonlit Katana', 'Sword', 22, 3, 5, 4, '/static/images/weapons/moonlit_katana.png'),
('Crimson Claymore', 'Sword', 24, 5, 2, 1, '/static/images/weapons/crimson_claymore.png'),
('Stormbringer Sword', 'Sword', 26, 6, 6, 2, '/static/images/weapons/stormbringer_sword.png'),
('Infernal Edge', 'Sword', 28, 5, 7, 3, '/static/images/weapons/infernal_edge.png'),
('Sword of Legends', 'Sword', 30, 7, 10, 5, '/static/images/weapons/sword_of_legends.png'),
('Woodcutter''s Axe', 'Axe', 3, 0, 0, 1, '/static/images/weapons/woodcutters_axe.png'),
('Iron Hatchet', 'Axe', 5, 1, 0, 2, '/static/images/weapons/iron_hatchet.png'),
('Steel Battleaxe', 'Axe', 7, 2, 0, 1, '/static/images/weapons/steel_battleaxe.png'),
('Bronze War Axe', 'Axe', 9, 3, 0, 1, '/static/images/weapons/bronze_war_axe.png'),
('Silver Chopper', 'Axe', 11, 4, 1, 2, '/static/images/weapons/silver_chopper.png'),
('Knight''s Axe', 'Axe', 13, 5, 0, 2, '/static/images/weapons/knights_axe.png'),
('Flame Reaver', 'Axe', 15, 4, 3, 1, '/static/images/weapons/flame_reaver.png'),
('Dragonbone Cleaver', 'Axe', 17, 5, 2, 2, '/static/images/weapons/dragonbone_cleaver.png'),
('Storm Axe', 'Axe', 19, 3, 5, 3, '/static/images/weapons/storm_axe.png'),
('Frostbreaker Axe', 'Axe', 21, 6, 4, 2, '/static/images/weapons/frostbreaker_axe.png'),
('Titan''s War Axe', 'Axe', 24, 7, 3, 1, '/static/images/weapons/titans_war_axe.png'),
('Axe of the Ancients', 'Axe', 28, 8, 6, 2, '/static/images/weapons/axe_of_the_ancients.png'),
('Simple Dagger', 'Dagger', 3, 0, 0, 7, '/static/images/weapons/simple_dagger.png'),
('Thief''s Blade', 'Dagger', 4, 1, 0, 8, '/static/images/weapons/thiefs_blade.png'),
('Stiletto', 'Dagger', 5, 1, 0, 9, '/static/images/weapons/stiletto.png'),
('Curved Knife', 'Dagger', 6, 1, 0, 10, '/static/images/weapons/curved_knife.png'),
('Shadow Dagger', 'Dagger', 7, 1, 1, 11, '/static/images/weapons/shadow_dagger.png'),
('Assassin''s Fang', 'Dagger', 8, 2, 0, 12, '/static/images/weapons/assassins_fang.png'),
('Venomblade', 'Dagger', 9, 1, 3, 11, '/static/images/weapons/venomblade.png'),
('Windcutter Dagger', 'Dagger', 10, 1, 0, 13, '/static/images/weapons/windcutter_dagger.png'),
('Spectral Dagger', 'Dagger', 11, 2, 4, 12, '/static/images/weapons/spectral_dagger.png'),
('Silent Death', 'Dagger', 12, 1, 2, 14, '/static/images/weapons/silent_death.png'),
('Nightshade Dagger', 'Dagger', 13, 2, 3, 14, '/static/images/weapons/nightshade_dagger.png'),
('Razor Fang', 'Dagger', 14, 1, 5, 15, '/static/images/weapons/razor_fang.png'),
('Blade of Whispers', 'Dagger', 15, 1, 4, 16, '/static/images/weapons/blade_of_whispers.png'),
('Soulpiercer', 'Dagger', 16, 2, 6, 15, '/static/images/weapons/soulpiercer.png'),
('Phantoms Edge', 'Dagger', 17, 1, 7, 17, '/static/images/weapons/phantoms_edge.png'),
('Traveler''s Staff', 'Staff', 1, 0, 10, 2, '/static/images/weapons/wooden_staff.png'),
('Apprentice''s Staff', 'Staff', 2, 0, 12, 2, '/static/images/weapons/apprentice_staff.png'),
('Mystic Branch', 'Staff', 2, 1, 14, 1, '/static/images/weapons/mystic_branch.png'),
('Sage''s Staff', 'Staff', 2, 0, 16, 2, '/static/images/weapons/sages_staff.png'),
('Enchanted Oak Staff', 'Staff', 3, 1, 18, 2, '/static/images/weapons/enchanted_oak_staff.png'),
('Arcane Rod', 'Staff', 1, 1, 20, 3, '/static/images/weapons/arcane_rod.png'),
('Warden''s Cane', 'Staff', 3, 1, 22, 2, '/static/images/weapons/wardens_cane.png'),
('Elderwood Staff', 'Staff', 2, 2, 24, 2, '/static/images/weapons/elderwood_staff.png'),
('Staff of Illumination', 'Staff', 1, 2, 26, 1, '/static/images/weapons/staff_of_illumination.png'),
('Sorcerer''s Staff', 'Staff', 3, 1, 28, 2, '/static/images/weapons/sorcerers_staff.png'),
('Staff of Wisdom', 'Staff', 2, 2, 30, 1, '/static/images/weapons/staff_of_wisdom.png'),
('Cursed Staff', 'Staff', 1, 2, 32, 3, '/static/images/weapons/cursed_staff.png'),
('Staff of the Magi', 'Staff', 2, 3, 34, 1, '/static/images/weapons/staff_of_the_magi.png'),
('Celestial Staff', 'Staff', 2, 2, 36, 1, '/static/images/weapons/celestial_staff.png'),
('Staff of the Heavens', 'Staff', 2, 3, 40, 2, '/static/images/weapons/staff_of_the_ancients.png');
